name: Auto Reply
on:
  issue_comment:
    types: [created]
# Re-registered to fix event subscription (E2E-IC-939997 rework 2026-02-24)
jobs:
  auto-reply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Processing comment: ${{ github.event.comment.body }}"
      - run: echo "Comment by ${{ github.event.comment.user.login }}"
